// This file is automatically generated. Do not edit it directly.

// Supabase removed. This file now exports the API base URL for the new backend.
export const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8000';

export const api = {
  // helper for axios or fetch can be implemented in frontend.
};